language: go

go:
  - 1.x

script: ./build.sh

deploy:
  provider: releases
  api-key: $apikey
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
