language: go

go:
  - 1.x

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic && ./build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api-key: $apikey
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
